name: Deploy to Pages

on:
  workflow_call:
    inputs:
      upload-path:
        required: true
        type: string
      build-command:
        type: string
        default: 'pnpm build'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install deps
        run: corepack enable && pnpm install
        shell: bash
      - run: ${{ inputs.build-command }}
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ inputs.upload-path }}
          
  deploy:
    needs: build
    runs-on: ubuntu-latest 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment